packages:
  - apps/*
  - packages/*
  - tooling/*

#catalog is for managing dependencies that are shared across packages
#which needs to have the same version across all packages

#note that catalog only servers as a guide, it does not enforce any rules
#when installing dependencies, pnpm will follow the package.json of each workspace

catalog:
  # Dev tooling
  eslint: ^9.19.0
  prettier: ^3.4.2
  tailwindcss: ^4.1.8
  "@tailwindcss/postcss": ^4.1.8
  typescript: ^5.7.3

  # Misc
  zod: ^3.24.1

  # Tanstack & tRPC
  "@tanstack/react-query": ^5.67.1
  "@trpc/client": ^11.0.0-rc.824
  "@trpc/tanstack-react-query": ^11.0.0-rc.824
  "@trpc/server": ^11.0.0-rc.824

catalogs:
  react19:
    react: 19.0.0
    react-dom: 19.0.0
    "@types/react": ^19.0.0
    "@types/react-dom": ^19.0.0
