name = "founderlog-webhook-handler"
main = "src/index.ts"


compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-09-23"

# Define a fixed port for development
[dev]
port = 5000

# Non-sensitive environment variables
[vars]
NODE_ENV = "production"
# Add any other non-sensitive variables here

# Production environment specific configuration
[env.production]
# Production specific non-sensitive environment variables
# vars = { SOME_VAR = "production-value" }

# Development environment specific configuration
[env.development]
# Development specific non-sensitive environment variables
# vars = { SOME_VAR = "development-value" }

# DO NOT put sensitive values in this file
# Instead, use wrangler secrets or the Cloudflare dashboard
# For sensitive values, use:
# - `wrangler secret put NAME` command to add individual secrets
# - `wrangler secret:bulk PUT_FILENAME` to add multiple secrets at once

# Secret variables that must be added via wrangler secret commands

# Specify service bindings like KV, Durable Objects, R2, etc. if needed
# For example, to use KV:
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" 